apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saadhussain07/devboard-gitops.git
    targetRevision: main
    path: devboard
  destination:
    server: https://kubernetes.default.svc
    namespace: devboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
